---
title: "Chi Zhang"
description: |
  PhD student at University of Oslo, researcher at Folkehelseinstituttet
site: distill::distill_website
---

Hi! Welcomd to my new website, build in [distill](https://rstudio.github.io/distill/). 

I am a researcher at the Department of Infectious Disease Epidemiology and Modeling, Norwegian Institute of Public Health (Folkehelseinstitutte). I mostly work on the development of an open-source health surveillance system, [Sykdomspulsen](https://www.fhi.no/hn/statistikk/sykdomspulsen/sykdomspulsen/). In addition I maintain and develop several R packages including [fhidata](https://github.com/folkehelseinstituttet/fhidata), [fhimaps](https://github.com/folkehelseinstituttet/fhimaps), [fhiplot](https://github.com/folkehelseinstituttet/fhiplot). 

In the meantime I am a PhD student at the [Oslo Center for Biostatistics and Epidemiology](https://www.med.uio.no/imb/english/research/centres/ocbe/), University of Oslo, Norway. My PhD work is focused on Electronic Health Records, generated from hospitals in particular. My current research interest is the use of EHR data for patient transfer tracking and visualisation with networks. 

You can find me on [twitter](https://twitter.com/Andreasheenn) or [github](https://github.com/andreaczhang). 