--- 
title: EHR projects
description: A brief introduction of my PhD projects on Electronic Health Records
date: "12/23/2020"
---


For my PhD, I work on EHR (Electronic Health Records) data from hospitals. EHR data can be any types of data that is generated in a healthcare setting: patient vital signs, drugs administered, demographics , billing information and/or images. I have worked on two hospital datasets: the public [MIMIC-III database](https://mimic.physionet.org) from a hospital in Boston, and a large Norwegian hospital in the greater Oslo area. 




## DTW-CP project 

This projects makes use of the time series data from the MIMIC-III dataset. Temporal EHR data such as physiological vital signs and lab test results are particularly challenging. Temporal EHR features typically have different sampling frequencies; such examples include heart rate (measured almost continuously) and blood test results (a few times during a patient’s entire stay). Different patients also have different length of stays. Existing approaches for temporal EHR sequence extraction either ignore the temporal pattern within features, or use a predefined window to select a section of the sequences without taking into account all the information. We propose a novel approach to tackle the issue of irregularly sampled, unequal length EHR time series using dynamic time warping and tensor decomposition.



## Patient transfer project 

This projects examines the patient transfer pattern at four departments (gastrointestinal surgical, gastrointestinal medical, orthopaedics, neurologic) over one year. We used network visualisation to identify the movement trajectory of patients and try to identify the similarity and differences.  



## Hospital acquired infection intervention project 

This project is largely a simulation based project using hospital acquired infection (HAI) as a case study. The key idea is to identify risk factors that are influential to the outcome, and make a hypothetical change to avert the outcome. 











